### ISSUE TITLE
wrong behavior with children property (Spring + width:auto)

### ISSUE THREAD

**Issue by abeauvois** [drcmda/react-spring#174] opened 2018-08-08 10:36 UTC
As shown here : https://codesandbox.io/s/jvqoo29mxy

If you click twice on the button,supposed to have 2 states : opened (width:auto) and closed (width:36), a 3rd state appears (width:0).

This happen only when I use the children={Content} way of doing it.

When doing this the classical way (render prop) the behavior is correct: https://codesandbox.io/s/mzp9jm6ywj

**Comment by drcmda** [comment] 2018-08-08 20:49
Duplicate of https://github.com/drcmda/react-spring/issues/153 

I'm on it, fix will be out very soon!

**Comment by drcmda** [comment] 2018-08-09 10:15
@abeauvois could you  try beta2 ? Here's your working example: https://codesandbox.io/s/4wvmz5kq54

**Closed** 2018-08-09 10:26 UTC

**Comment by abeauvois** [comment] 2018-08-14 10:07
works like a charm :)
